sonar.projectKey=Only-Raw-Data_soen390-only-raw-data
sonar.organization=only-raw-data
sonar.host.url=https://sonarcloud.io

sonar.sources=app,components,constants
sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.config.js,**/*.config.ts,assets/**,**/__tests__/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.coverage.exclusions=**/node_modules/**,**/coverage/**,**/*.config.js,**/*.config.ts,assets/**,app/_layout.tsx,app/(tabs)/_layout.tsx,app/+html.tsx,app/+not-found.tsx,app/modal.tsx,app/types/**,components/**,constants/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
