sonar.projectKey=Only-Raw-Data_soen390-only-raw-data
sonar.organization=only-raw-data
sonar.host.url=https://sonarcloud.io

sonar.sources=app,components,constants
sonar.tests=app,components,constants
sonar.test.inclusions=**/__tests__/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.config.js,**/*.config.ts,assets/**
sonar.coverage.exclusions=**/node_modules/**,**/coverage/**,**/*.config.js,**/*.config.ts,assets/**,**/__tests__/**,**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
