sonar.projectKey=Only-Raw-Data_soen390-only-raw-data
sonar.organization=only-raw-data
sonar.host.url=https://sonarcloud.io

sonar.sources=app,components,constants,hooks,services,utils,context
sonar.tests=app/components/__tests__,app/hooks/__tests__,app/services/__tests__,app/utils/__tests__,app/context/__tests__,components/__tests__

sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.config.js,**/*.config.ts,assets/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8

