name: React Native CI

on:
  workflow_dispatch:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install
        working-directory: campus-guide

      - name: Run Tests
        working-directory: campus-guide
        run: npm test -- --coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        with:
          projectBaseDir: campus-guide
          args: >
            -Dsonar.projectKey= ${{ secrets.project_KEY }}
            -Dsonar.organization=only-raw-data
            -Dsonar.host.url=https://sonarcloud.io/organizations/only-raw-data/projects
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
         


      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
