name: React Native CI

on:
  workflow_dispatch:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install
        working-directory: campus-guide

      - name: Run Tests
        working-directory: campus-guide
        run: npm test -- --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@<671740ac38dd9b0130fbe1cec585b89eea48d3de>
        with:
          token: ${{ secrets.CODECOV_TOKEN }}